# Generated by Django 3.2.20 on 2024-07-07 01:37

from django.db import migrations, models
# import django.db.models.deletion


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunPython(noop),
    ]
