--INSERT INTO User
--    (username, email, password, created_at, updated_at)
--VALUES
--    ('juhee1', 'juhee1@example.com', 'password_1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--    ('juhee2', 'juhee2@example.com', 'password_2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

--INSERT INTO Label
--(user_id, label_name, created_at, updated_at)
--VALUES
--(1, '친구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(1, '회사', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

--INSERT INTO ContactLabel
--(contact_id, label_id)
--VALUES
--(1, 1),
--(2, 1),
--(3, 1),
--(4, 1),
--(5, 1),
--(3, 2),
--(4, 2),
--(5, 2);